//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.16 at 05:14:31 PM IST 
//


package com.infosys.ellsie.data.arxiv;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for arXivType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="arXivType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="created" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="updated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="authors" type="{http://arxiv.org/OAI/arXiv/}authorsType" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="msc-class" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="acm-class" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="report-no" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="journal-ref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="categories" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="doi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="proxy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="license" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "arXivType", propOrder = {
    "idOrCreatedOrUpdated"
})
public class ArXivType {

    @XmlElementRefs({
        @XmlElementRef(name = "report-no", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "id", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "authors", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "comments", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "proxy", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "created", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "updated", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "doi", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "categories", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "msc-class", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "license", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "title", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "journal-ref", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "abstract", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "acm-class", namespace = "http://arxiv.org/OAI/arXiv/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> idOrCreatedOrUpdated;

    /**
     * Gets the value of the idOrCreatedOrUpdated property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idOrCreatedOrUpdated property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdOrCreatedOrUpdated().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link AuthorsType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getIdOrCreatedOrUpdated() {
        if (idOrCreatedOrUpdated == null) {
            idOrCreatedOrUpdated = new ArrayList<JAXBElement<?>>();
        }
        return this.idOrCreatedOrUpdated;
    }

}
