//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.16 at 05:14:31 PM IST 
//


package com.infosys.ellsie.data.arxiv;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the data.arxiv package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ArXiv_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "arXiv");
    private final static QName _ArXivTypeUpdated_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "updated");
    private final static QName _ArXivTypeAuthors_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "authors");
    private final static QName _ArXivTypeDoi_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "doi");
    private final static QName _ArXivTypeId_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "id");
    private final static QName _ArXivTypeCategories_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "categories");
    private final static QName _ArXivTypeReportNo_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "report-no");
    private final static QName _ArXivTypeProxy_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "proxy");
    private final static QName _ArXivTypeLicense_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "license");
    private final static QName _ArXivTypeTitle_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "title");
    private final static QName _ArXivTypeAcmClass_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "acm-class");
    private final static QName _ArXivTypeJournalRef_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "journal-ref");
    private final static QName _ArXivTypeMscClass_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "msc-class");
    private final static QName _ArXivTypeAbstract_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "abstract");
    private final static QName _ArXivTypeCreated_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "created");
    private final static QName _ArXivTypeComments_QNAME = new QName("http://arxiv.org/OAI/arXiv/", "comments");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: data.arxiv
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArXivType }
     * 
     */
    public ArXivType createArXivType() {
        return new ArXivType();
    }

    /**
     * Create an instance of {@link AuthorType }
     * 
     */
    public AuthorType createAuthorType() {
        return new AuthorType();
    }

    /**
     * Create an instance of {@link AuthorsType }
     * 
     */
    public AuthorsType createAuthorsType() {
        return new AuthorsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArXivType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "arXiv")
    public JAXBElement<ArXivType> createArXiv(ArXivType value) {
        return new JAXBElement<ArXivType>(_ArXiv_QNAME, ArXivType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "updated", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeUpdated(String value) {
        return new JAXBElement<String>(_ArXivTypeUpdated_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "authors", scope = ArXivType.class)
    public JAXBElement<AuthorsType> createArXivTypeAuthors(AuthorsType value) {
        return new JAXBElement<AuthorsType>(_ArXivTypeAuthors_QNAME, AuthorsType.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "doi", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeDoi(String value) {
        return new JAXBElement<String>(_ArXivTypeDoi_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "id", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeId(String value) {
        return new JAXBElement<String>(_ArXivTypeId_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "categories", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeCategories(String value) {
        return new JAXBElement<String>(_ArXivTypeCategories_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "report-no", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeReportNo(String value) {
        return new JAXBElement<String>(_ArXivTypeReportNo_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "proxy", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeProxy(String value) {
        return new JAXBElement<String>(_ArXivTypeProxy_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "license", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeLicense(String value) {
        return new JAXBElement<String>(_ArXivTypeLicense_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "title", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeTitle(String value) {
        return new JAXBElement<String>(_ArXivTypeTitle_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "acm-class", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeAcmClass(String value) {
        return new JAXBElement<String>(_ArXivTypeAcmClass_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "journal-ref", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeJournalRef(String value) {
        return new JAXBElement<String>(_ArXivTypeJournalRef_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "msc-class", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeMscClass(String value) {
        return new JAXBElement<String>(_ArXivTypeMscClass_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "abstract", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeAbstract(String value) {
        return new JAXBElement<String>(_ArXivTypeAbstract_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "created", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeCreated(String value) {
        return new JAXBElement<String>(_ArXivTypeCreated_QNAME, String.class, ArXivType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arxiv.org/OAI/arXiv/", name = "comments", scope = ArXivType.class)
    public JAXBElement<String> createArXivTypeComments(String value) {
        return new JAXBElement<String>(_ArXivTypeComments_QNAME, String.class, ArXivType.class, value);
    }

}
