//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.16 at 05:14:31 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://arxiv.org/OAI/arXiv/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.infosys.ellsie.data.arxiv;
