# Connection parameters
readFilePath: D:/arxiv/arxiv/
threadPoolSize: 2
fileBatchSize: 1000
writeFilePath: d:/arxiv2
arxivURL: export.arxiv.org
proxyHost: 10.68.248.102
proxyPort: 80
commitInMs: 10000
sparkUrl: local